name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MrZilinXiao
          template: classic
          base: header, repositories
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
          plugin_notable: yes
          plugin_notable_repositories: yes
